---
apiVersion: v1
kind: Namespace
metadata:
  name: nginx-test
---
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: nginx-issuer
  namespace: nginx-test
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: nginx-tls-cert
  namespace: nginx-test
spec:
  dnsNames:
  - nginx.gateway.cluster-a.dev-team.clusters.xcc.test
  issuerRef:
    kind: Issuer
    name: nginx-issuer
  secretName: nginx-tls-secret
