---
apiVersion: v1
kind: Namespace
metadata:
  name: cross-cluster-connectivity
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: connectivity-dns
  namespace: cross-cluster-connectivity
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: connectivity-dns
  namespace: cross-cluster-connectivity
  labels:
    app: connectivity-dns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: connectivity-dns
  template:
    metadata:
      labels:
        app: connectivity-dns
    spec:
      serviceAccountName: connectivity-dns
      containers:
      - name: connectivity-dns
        image: ghcr.io/vmware-tanzu/cross-cluster-connectivity/connectivity-dns:dev
        # remove this when testing on a remote cluster
        imagePullPolicy: Never
        args: [ "-conf", "/etc/coredns/Corefile" ]
        volumeMounts:
        - name: config-volume
          mountPath: /etc/coredns
          readOnly: true
        ports:
        - containerPort: 53
          name: dns
          protocol: UDP
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
      volumes:
        - name: config-volume
          configMap:
            name: connectivity-dns-corefile
            items:
            - key: Corefile
              path: Corefile
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: connectivity-dns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: connectivity-dns
subjects:
  - kind: ServiceAccount
    name: connectivity-dns
    namespace: cross-cluster-connectivity
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: connectivity-dns
rules:
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - list
      - watch
      - get
---
apiVersion: v1
kind: Service
metadata:
  name: connectivity-dns
  namespace: cross-cluster-connectivity
  labels:
    app: connectivity-dns
spec:
  selector:
    app: connectivity-dns
  type: ClusterIP
  ports:
  - port: 53
    targetPort: 53
    protocol: TCP
    name: dns-tcp
  - port: 53
    targetPort: 53
    protocol: UDP
    name: dns
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: connectivity-dns-corefile
  namespace: cross-cluster-connectivity
data:
  Corefile: |
    xcc.test {
        log
        errors
        health {
          lameduck 5s
        }
        crosscluster
        ready
        prometheus :9153
        cache 30
        reload
        loop
        loadbalance
        whoami
    }
