---
apiVersion: v1
kind: Namespace
metadata:
  name: xcc-dns
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: xcc-dns-controller
  namespace: xcc-dns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xcc-dns-controller
  namespace: xcc-dns
  labels:
    app: xcc-dns-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xcc-dns-controller
  template:
    metadata:
      labels:
        app: xcc-dns-controller
    spec:
      serviceAccountName: xcc-dns-controller
      containers:
      - name: xcc-dns-controller
        image: gcr.io/tanzu-xcc/xcc-dns-controller:dev
        args: []
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: DOMAIN_SUFFIX
          value: xcc.test
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: xcc-dns-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: xcc-dns-controller
subjects:
- kind: ServiceAccount
  name: xcc-dns-controller
  namespace: xcc-dns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: xcc-dns-controller
rules:
- apiGroups:
  - "cluster.x-k8s.io"
  resources:
  - clusters
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - "connectivity.tanzu.vmware.com"
  resources:
  - gatewaydns
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - list
  - watch
  - get
