---
apiVersion: v1
kind: Namespace
metadata:
  name: xcc-dns
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dns-config-patcher
  namespace: xcc-dns
---
apiVersion: batch/v1
kind: Job
metadata:
  name: dns-config-patcher
  namespace: xcc-dns
spec:
  backoffLimit: 10
  ttlSecondsAfterFinished: 120
  template:
    metadata:
      labels:
        app: dns-config-patcher
    spec:
      serviceAccountName: dns-config-patcher
      restartPolicy: OnFailure
      containers:
      - name: dns-config-patcher
        image: gcr.io/tanzu-xcc/dns-config-patcher:dev
        env:
        - name: "DNS_SERVICE_NAMESPACE"
          value: "xcc-dns"
        - name: "DNS_SERVICE_NAME"
          value: "dns-server"
        - name: "COREFILE_CONFIGMAP_NAMESPACE"
          value: "kube-system"
        - name: "COREFILE_CONFIGMAP_NAME"
          value: "coredns"
        - name: "DOMAIN_SUFFIX"
          value: "xcc.test"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dns-config-patcher
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: system-corefile-updater
subjects:
- kind: ServiceAccount
  name: dns-config-patcher
  namespace: xcc-dns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dns-config-patcher
  namespace: xcc-dns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: capi-dns-service-watcher
subjects:
- kind: ServiceAccount
  name: dns-config-patcher
  namespace: xcc-dns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: system-corefile-updater
  namespace: kube-system
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs:
  - get
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: capi-dns-service-watcher
  namespace: xcc-dns
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs:
  - get
