name: Test
on: push
jobs:
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.13.1'
      - run: go get -u github.com/onsi/ginkgo/ginkgo
      - run: make test-unit
  run-e2e-tests:
    name: Run End-to-end Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.13.1'
      - run: go get -u github.com/onsi/ginkgo/ginkgo
      - run: make build-images
      - name: Download clusterctl
        run: |
          sudo wget -O /usr/local/bin/clusterctl "https://github.com/kubernetes-sigs/cluster-api/releases/download/v${VERSION}/clusterctl-linux-amd64"
          sudo chmod +x /usr/local/bin/clusterctl
        env:
          VERSION: 0.3.10
      - name: Download ytt
        run: |
          sudo wget -O /usr/local/bin/ytt "https://github.com/k14s/ytt/releases/download/v${VERSION}/ytt-linux-amd64"
          sudo chmod +x /usr/local/bin/ytt
        env:
          VERSION: 0.30.0
      - run: make e2e-up
      - run: make test-connectivity
