name: Test
on: push
jobs:
  check-license:
    name: Check License
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          # pinning to 1.15.x, can be depinned when https://github.com/golang/go/issues/44129 is resolved.
          go-version: '~1.15.12'
      - run: go get -u github.com/google/addlicense
      - run: make checklicense
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          # pinning to 1.15.x, can be depinned when https://github.com/golang/go/issues/44129 is resolved.
          go-version: '~1.15.12'
      - run: go get -u github.com/onsi/ginkgo/ginkgo
      - run: make test-unit
  run-e2e-tests:
    name: Run End-to-end Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
      - uses: actions/setup-go@v2
        with:
          # pinning to 1.15.x, can be depinned when https://github.com/golang/go/issues/44129 is resolved.
          go-version: '~1.15.12'
      - run: go get -u github.com/onsi/ginkgo/ginkgo
      # pinning to 1.15.x for aformentioned reasons
      - run: make build-images GOBUILD_VERSION=1.15.12-buster
      - name: Download clusterctl
        run: |
          sudo wget -O /usr/local/bin/clusterctl "https://github.com/kubernetes-sigs/cluster-api/releases/download/v${VERSION}/clusterctl-linux-amd64"
          sudo chmod +x /usr/local/bin/clusterctl
        env:
          VERSION: 0.3.10
      - name: Download ytt
        run: |
          sudo wget -O /usr/local/bin/ytt "https://github.com/k14s/ytt/releases/download/v${VERSION}/ytt-linux-amd64"
          sudo chmod +x /usr/local/bin/ytt
        env:
          VERSION: 0.30.0
      - name: Download kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
        env:
          VERSION: 0.10.0
      - name: Download kind
        run: |
          sudo wget -O /usr/local/bin/kind "https://kind.sigs.k8s.io/dl/v${VERSION}/kind-linux-amd64"
          sudo chmod +x /usr/local/bin/kind
        env:
          VERSION: 0.10.0
      - name: Download kustomize
        run: |
          GO111MODULE=on go get sigs.k8s.io/kustomize/kustomize/v3
      - run: make e2e-up
      - name: Run e2e tests
        run: |
          set +e
          make test-cluster-api-dns
          exitStatus=$?
          if [ ${exitStatus} -ne 0 ]; then
            for entry in "${PWD}"/test/clusterapidns/logs/**/*; do
              echo "::group::${entry}"
              cat "${entry}"
              echo "::endgroup::"
            done
          fi
          set -e
          exit ${exitStatus}
